@backend_HostAddress = http://localhost:5266

GET {{backend_HostAddress}}/api/places
Accept: application/json
###

GET {{backend_HostAddress}}/api/user

###

POST {{backend_HostAddress}}/api/user/register
Content-Type: application/json

{
  "Username": "admin",
  "Password": "admin"
}
