@backend_HostAddress = http://localhost:5266

GET {{backend_HostAddress}}/api/places
Accept: application/json
###

GET {{backend_HostAddress}}/api/user

###

POST {{backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Username": "check",
  "Password": "vsd"
}

###
PUT {{backend_HostAddress}}/api/user/password
Content-Type: application/json

{
  "Username": "a",
  "NewPassword": "123"
}



###
DELETE {{backend_HostAddress}}/api/user/7